export const STRINGS = {
  // Navigation
  CATALOGUE: 'Catalogue',
  SESSIONS: 'Sessions',
  PERSONNEL: 'Personnel',
  
  // Common
  RECHERCHER: 'Rechercher...',
  AJOUTER: 'Ajouter',
  MODIFIER: 'Modifier',
  SUPPRIMER: 'Supprimer',
  ANNULER: 'Annuler',
  ENREGISTRER: 'Enregistrer',
  CREER: 'Créer',
  METTRE_A_JOUR: 'Mettre à jour',
  SUCCES: 'Succès',
  ERREUR: 'Erreur',
  CHARGEMENT: 'Chargement...',
  REDUIRE:'Reduire',
  DETAILS:'Details',
  OUI:'Oui',
  NON:'Non',
  RETIRER:'Retirer',
  RESULTATS_SESSION: 'Résultats de la Session',
  ERREUR_EXPORT_PDF: 'Une erreur est survenue lors de l\'exportation du PDF.',
  
  // Catalogue
  CATALOGUE_FORMATIONS: 'Catalogue des Formations',
  CREER_FORMATION: 'Créer une Formation',
  MODIFIER_FORMATION: 'Modifier la Formation',
  AUCUNE_FORMATION: 'Aucune formation disponible',
  CREER_PREMIERE_FORMATION: 'Créer votre première formation',
  FORMATION_CREEE: 'Formation créée avec succès',
  FORMATION_MISE_A_JOUR: 'Formation mise à jour avec succès',
  FORMATION_SUPPRIMEE: 'Formation supprimée avec succès',
  CONFIRMER_SUPPRESSION_FORMATION: 'Êtes-vous sûr de vouloir supprimer cette formation ?',
  
  // Formation Details
  NOM_FORMATION: 'Nom de la Formation',
  DESCRIPTION: 'Description',
  OBJECTIF_PEDAGOGIQUE: 'Objectif Pédagogique',
  PREREQUIS: 'Prérequis',
  TYPE:'Type de Session',
  CATEGORIE: 'Catégorie',
  CERTIFIANT: 'Certifiant',
  NON_CERTIFIANT: 'Non Certifiant',
  COMPETENCES: 'Compétences',
  NOUVELLE_COMPETENCE: 'Nouvelle Compétence',
  AUCUNE_COMPETENCE: 'Aucune compétence ajoutée',
  INTERNE: 'Interne',
  EXTERNE: 'Externe',
  CONFIRMER_SELECTION: 'Confirm Selection',

  // Validation
  NOM_REQUIS: 'Le nom de la formation est requis',
  DESCRIPTION_REQUISE: 'La description est requise',
  OBJECTIF_REQUIS: 'L\'objectif pédagogique est requis',
  COMPETENCES_REQUISES: 'Au moins une compétence est requise',
  
  // Sessions
  SESSIONS_FORMATION: 'Sessions de Formation',
  CREER_SESSION: 'Créer Session',
  AUCUNE_SESSION: 'Aucune session trouvée',
  SESSION_CREEE: 'Session créée avec succès',
  SESSION_SUPPRIMEE: 'Session supprimée avec succès',
  CONFIRMER_SUPPRESSION_SESSION: 'Êtes-vous sûr de vouloir supprimer cette session ?',
  AVEC_CERTIFICAT: 'Avec Certificat',
  SANS_CERTIFICAT: 'Sans Certificat',
  TYPE_FORMATION:'Type de formation',
  RECHERCHER_SESSION:'Rechercher une session',

  // Session Details
  DATE_DEBUT: 'Date de Début',
  DATE_FIN: 'Date de Fin',
  FORMATEUR: 'Formateur',
  DUREE_FORMATION: 'Durée de la Formation',
  CABINET_FORMATION: 'Cabinet de Formation',
  PARTICIPANTS: 'Participants',
  SELECTIONNER_FORMATEUR: 'Sélectionner un Formateur',
  SELECTIONNER_CABINET: 'Sélectionner un Cabinet',
  SELECTIONNER_PARTICIPANTS: 'Sélectionner les Participants',
  RECHERCHER_FORMATEUR: 'Rechercher un formateur...',
  RECHERCHER_CABINET: 'Rechercher un cabinet...',
  RECHERCHER_PARTICIPANT: 'Rechercher un participant...',
  AUCUN_FORMATEUR: 'Aucun formateur trouvé',
  AUCUN_CABINET: 'Aucun cabinet trouvé',
  AUCUN_PARTICIPANT: 'Aucun participant trouvé',
  DETAILS_SESSION:'Détails de la Session',
  
  // Session Status
  EN_ATTENTE: 'En Attente',
  EN_COURS: 'En Cours',
  TERMINEE: 'Terminée',
  ANNULEE: 'Annulée',
  
  // Training Management
  GESTION_FORMATION: 'Gestion de Formation',
  MEMBRES: 'Membres',
  PRESENCES: 'Présences',
  CERTIFICATION: 'Certification',
  MEMBRES_FORMATION_INTERNE: 'Membres - Formation Interne',
  MEMBRES_FORMATION_EXTERNE: 'Membres - Formation Externe',
  
  // Participants
  AJOUTER_PARTICIPANT: 'Ajouter un Participant',
  PARTICIPANT_AJOUTE: 'Participant ajouté avec succès',
  PARTICIPANT_SUPPRIME: 'Participant supprimé avec succès',
  CONFIRMER_SUPPRESSION_PARTICIPANT: 'Êtes-vous sûr de vouloir supprimer ce participant ?',
  RECHERCHER_AGENT: 'Rechercher un agent...',
  NOMBRE_PARTICIPANTS: 'Nombre de Participants',
  CONFIRMER_RETRAIT:'Confirmer le retrait',
  CONFIRMER_RETRAIT_PARTICIPANT:'Confirmer le retrait du participant',
  
  // Presence Management
  GESTION_PRESENCES: 'Gestion des Présences',
  SELECTIONNER_DATE: 'Sélectionner une Date',
  PRESENCE_DU: 'Présence du',
  PRESENT: 'Présent',
  ABSENT: 'Absent',
  PRESENCE: 'Présence',
  TAUX_PRESENCE: 'Taux de Présence',
  MARQUER_TOUS_PRESENTS: 'Tous Présents',
  MARQUER_TOUS_ABSENTS: 'Tous Absents',
  ENREGISTRER_PRESENCES: 'Enregistrer les Présences',
  PRESENCES_ENREGISTREES: 'Présences enregistrées avec succès',
  SELECTIONNER_DATE_PRESENCE: 'Sélectionnez une date pour gérer les présences',
  DATE_REQUISE: 'Une date doit être sélectionnée',
  
  // Certification
  MATRICE_EVALUATION: 'Matrice d\'Évaluation',
  PARTICIPANT: 'Participant',
  MOYENNE: 'Moyenne',
  STATUT: 'Statut',
  ADMIS: 'Admis',
  NON_ADMIS: 'Non Admis',
  NOTE_INVALIDE: 'La note doit être comprise entre 0 et 20',
  ENREGISTRER_EVALUATIONS: 'Enregistrer les Évaluations',
  EVALUATIONS_ENREGISTREES: 'Évaluations enregistrées avec succès',
  EXPORTER_RESULTATS_PDF: 'Exporter en PDF',
  GENERER_CERTIFICATS: 'Générer les Certificats',
  NOMBRE_COMPETENCES: 'Nombre de Compétences',
  ACTIONS: 'Actions',
  
  // Personnel
  GESTION_PERSONNEL: 'Gestion du Personnel',
  CHOISIR_OPTION: 'Choisissez une option ci-dessous',
  GESTION_AGENTS: 'Gestion des Agents',
  GESTION_CABINETS: 'Gestion des Cabinets',
  
  // Agents
  AJOUTER_AGENT: 'Ajouter un agent',
  RECHERCHER_AGENT: 'Rechercher un agent...',
  AUCUN_AGENT: 'Aucun agent trouvé',
  CREER_AGENT: 'Créer un Agent',
  MODIFIER_AGENT: 'Modifier l\'Agent',
  AGENT_CREE: 'Agent créé avec succès',
  AGENT_MIS_A_JOUR: 'Agent mis à jour avec succès',
  AGENT_SUPPRIME: 'Agent supprimé avec succès',
  CONFIRMER_SUPPRESSION_AGENT: 'Êtes-vous sûr de vouloir supprimer cet agent ?',
  MATRICULE: 'Matricule',
  NOM: 'Nom',
  FONCTION: 'Fonction',
  DATE_EMBAUCHE: 'Date d\'Embauche',
  EST_FORMATEUR: 'Est Formateur',
  DOMAINE_FORMATION: 'Domaine de Formation',
  DOMAINE_REQUIS: 'Le domaine de formation est requis pour un formateur',
  
  // Cabinets
  CABINET:'Cabinet',
  AJOUTER_CABINET: 'Ajouter un cabinet',
  RECHERCHER_CABINET: 'Rechercher un cabinet...',
  AUCUN_CABINET: 'Aucun cabinet trouvé',
  CREER_CABINET: 'Créer un Cabinet',
  MODIFIER_CABINET: 'Modifier le Cabinet',
  CABINET_CREE: 'Cabinet créé avec succès',
  CABINET_MIS_A_JOUR: 'Cabinet mis à jour avec succès',
  CABINET_SUPPRIME: 'Cabinet supprimé avec succès',
  CONFIRMER_SUPPRESSION_CABINET: 'Êtes-vous sûr de vouloir supprimer ce cabinet ?',
  TELEPHONE: 'Téléphone',
  EMPLACEMENT: 'Emplacement',
  DOMAINE: 'Domain',
  
  // Errors
  ERREUR_CHARGEMENT: 'Erreur de Chargement',
  ERREUR_SAUVEGARDE: 'Erreur de Sauvegarde',
  ERREUR_SUPPRESSION: 'Erreur de Suppression',
  ERREUR_AJOUT: 'Erreur d\'Ajout',
  ERREUR_RESEAU: 'Erreur de réseau. Vérifiez votre connexion.',
  ERREUR_SUPPRESSION_PARTICIPANT: 'Erreur de suppression',
  ERREUR_SUPPRESSION: 'Erreur de Suppression',
  CATALOGUE_EN_COURS_UTILISATION: 'Impossible de supprimer cette formation car elle est utilisée dans une ou plusieurs sessions.',
  
  // Development
  EN_DEVELOPPEMENT: 'En Développement',
  FONCTIONNALITE_FUTUR: 'Cette fonctionnalité sera disponible dans une future version.',
  EXPORT_PDF_FUTUR: 'L\'export PDF sera disponible prochainement.',
  GENERATION_CERTIFICATS_FUTUR: 'La génération de certificats sera disponible prochainement.',
  
  // Confirmations
  CONFIRMER_SUPPRESSION: 'Confirmer la Suppression',
  INFORMATIONS_GENERALES: 'Informations Générales',
};
